version: 2
jobs:
  build:
    working_directory: ~/jsc-android-buildscripts
    machine: true
    environment:
      MAKEFLAGS: "-i"
      JVM_OPTS: -Xmx3200m
      APP_PLATFORM: android-16
      SDK_VERSION: sdk-tools-linux-3859397.zip
      NDK_VERSION: r16
      ANDROID_HOME: /home/circleci/android-sdk
      ANDROID_NDK: /home/circleci/android-ndk
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: install android sdk
          command: |
            curl --silent --show-error --location --fail --retry 3 --output /tmp/${SDK_VERSION} https://dl.google.com/android/repository/${SDK_VERSION} && \
              mkdir -p ${ANDROID_HOME} && \
              unzip -q /tmp/${SDK_VERSION} -d ${ANDROID_HOME} && \
              rm /tmp/${SDK_VERSION}
            export PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
            mkdir ~/.android && echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
            yes | sdkmanager --licenses && sdkmanager --update
            sdkmanager \
              "tools" \
              "platform-tools" \
              "emulator" \
              "extras;android;m2repository" \
              "extras;google;m2repository" \
              "extras;google;google_play_services"
            sdkmanager \
              "build-tools;25.0.3" \
              "build-tools;27.0.3"
            sdkmanager "platforms;android-27"
      - run:
          name: install android ndk
          command: |
            export PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
            mkdir /tmp/android-ndk-tmp && \
              cd /tmp/android-ndk-tmp && \
              wget -q https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip &&
              unzip -q android-ndk-${NDK_VERSION}-linux-x86_64.zip && \
              mv ./android-ndk-${NDK_VERSION} ${ANDROID_NDK} && \
              cd ${ANDROID_NDK} && \
              rm -rf /tmp/android-ndk-tmp
            sdkmanager \
              "lldb;3.0" \
              "cmake;3.6.4111459"
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking yes\n" > ~/.ssh/config
      - run:
          name: test ndk
          command: |
            cd /home/circleci && git clone git@github.com:AndreySK4/libsampso.git ~/libsampso
            cd ~/libsampso && git submodule update --init
            cd ${ANDROID_NDK} && ./android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-objdump -T libsamp.so | less
      - run:
          name: LS
          command: cd /home/circleci/libsampso && ls
      - run:
          name: Muta artefactu
          command: |
            mkdir /tmp/artifacts
            mv /home/circleci/libsampso/* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
